set_installer_setting:
  description: Set an installer setting on the Solax inverter.
  fields:
    setting:
      description: Key of the setting to modify.
      example: feed_in_limit
    value:
      description: Value to apply.
      example: 50
    host:
      description: IP address or hostname of the inverter. Required when multiple inverters are configured.
      example: 192.168.1.100
    confirm:
      description: Must be true to apply the change.
      example: true

get_installer_settings:
  description: Retrieve all installer settings from the Solax inverter.
  fields:
    host:
      description: IP address or hostname of the inverter. Required when multiple inverters are configured.
      example: 192.168.1.100
